import type { CSSProperties } from "react";
import { iranGlobals } from "@/src/config/iran.globals";
import { iranTheme } from "@/src/themes/iran";

export function getThemeStyleVars(): CSSProperties {
  return {
    "--color-bg": iranTheme.color.bg,
    "--color-bg-top": iranTheme.color.bgTop,
    "--color-bg-deep": iranTheme.color.bgDeep,
    "--color-foreground": iranTheme.color.foreground,
    "--color-foreground-soft": iranTheme.color.foregroundSoft,
    "--color-primary": iranTheme.color.primary,
    "--color-primary-soft": iranTheme.color.primarySoft,
    "--color-primary-strong": iranTheme.color.primaryStrong,
    "--color-secondary": iranTheme.color.secondary,
    "--color-danger": iranTheme.color.danger,
    "--color-surface": iranTheme.color.surface,
    "--color-surface-strong": iranTheme.color.surfaceStrong,
    "--color-surface-accent": iranTheme.color.surfaceAccent,
    "--color-border-soft": iranTheme.color.borderSoft,
    "--color-border-strong": iranTheme.color.borderStrong,
    "--color-grid-line": iranTheme.color.gridLine,
    "--color-glow": iranTheme.color.glow,
    "--surface-glass": iranTheme.surface.glass,
    "--surface-stage": iranTheme.surface.stage,
    "--surface-accent": iranTheme.surface.accent,
    "--surface-shell": iranTheme.surface.shell,
    "--shadow-soft": iranTheme.shadow.soft,
    "--shadow-card": iranTheme.shadow.card,
    "--shadow-hero": iranTheme.shadow.hero,
    "--shadow-glow": iranTheme.shadow.glow,
    "--page-container": `${iranGlobals.sizing.containerWidth}px`,
    "--page-container-x": iranGlobals.sizing.containerX,
    "--section-y": iranGlobals.sizing.sectionY,
    "--section-y-tight": iranGlobals.sizing.sectionYTight,
    "--hero-top": iranGlobals.sizing.heroTop,
    "--hero-bottom": iranGlobals.sizing.heroBottom,
    "--grid-gap": iranGlobals.sizing.gridGap,
    "--card-padding": iranGlobals.sizing.cardPadding,
    "--button-min-height": iranGlobals.sizing.buttonMinHeight,
    "--header-height": iranGlobals.sizing.headerHeight,
    "--header-height-mobile": iranGlobals.sizing.headerHeightMobile,
    "--radius-sm": iranGlobals.sizing.radii.sm,
    "--radius-md": iranGlobals.sizing.radii.md,
    "--radius-lg": iranGlobals.sizing.radii.lg,
    "--radius-xl": iranGlobals.sizing.radii.xl,
    "--radius-pill": iranGlobals.sizing.radii.pill,
    "--type-display": iranGlobals.typography.display,
    "--type-heading": iranGlobals.typography.heading,
    "--type-subheading": iranGlobals.typography.subheading,
    "--type-card-title": iranGlobals.typography.cardTitle,
    "--type-body-lg": iranGlobals.typography.bodyLg,
    "--type-body": iranGlobals.typography.body,
    "--type-label": iranGlobals.typography.label,
    "--type-meta": iranGlobals.typography.meta,
    "--type-metric": iranGlobals.typography.metric,
    "--type-stat": iranGlobals.typography.stat,
    "--font-body": iranTheme.font.body,
    "--font-display": iranTheme.font.display,
    "--font-mono": iranTheme.font.mono,
    "--motion-fast": `${iranTheme.motion.durationFast}ms`,
    "--motion-base": `${iranTheme.motion.durationBase}ms`,
    "--motion-slow": `${iranTheme.motion.durationSlow}ms`,
    "--motion-loop": `${iranTheme.motion.durationLoop}ms`,
    "--ease-standard": iranTheme.motion.easingStandard,
    "--ease-entrance": iranTheme.motion.easingEntrance,
    "--ease-emphasis": iranTheme.motion.easingEmphasis,
  } as CSSProperties;
}

